"""SCAPS-1D 엔진 — 페로브스카이트 문헌 표준 1D 시뮬레이터 (겐트대, 연구용 무료).

강점: 계면 결함(재결합 속도 S)의 네이티브 지원 → 우리 COMSOL IDL(τ=d/S) 구현의
독립 대조군. 배포는 이메일 신청(비공개 아카이브)이라 설치는 사용자 몫.

.def(소자 정의) 파일 포맷은 버전 의존 바이너리성 텍스트라 **앱이 창작하지 않는다**
(임의 포맷 생성 금지 원칙). 대신:
  export : ① '레시피'(GUI에 입력할 물성 표 — materials.json 매핑, 출처 포함)
           ② SCAPS 스크립트 초안(.script — 액션 문법은 ⚠️ 첫 실행 검증)
           → 사용자가 GUI에서 소자를 한 번 만들어 .def로 저장하면, 이후 스크립트가
             그 .def를 불러 배치 실행 (SCAPS의 표준 사용 흐름)
  local  : scaps.exe에 스크립트 전달 시도 (⚠️ CLI 구동 방식 첫 실행 검증)
  import : SCAPS이 저장한 I-V(.iv)/QE(.qe) 파일 업로드 → 지표·플롯 (이건 즉시 사용 가능)
"""
import re
import subprocess
import time
from pathlib import Path

import numpy as np

from .. import jobs
from . import common, find_scaps


def _recipe_md(params, log):
    """GUI 입력용 물성 표 — materials.json에서 (SCAPS 입력 항목 명칭으로 변환)."""
    rows = []
    header = ("| 항목 (SCAPS 표기) | " + " | ".join(["SnO2 (ETL)", "MAPbI3 (흡수층)", "NiOx (HTL)"]) + " |")
    sep = "|---|---|---|---|"
    mats = [common.material("sno2"), common.material("mapbi3"), common.material("niox")]
    v = common.si_value

    def row(label, key, conv=lambda x: x, unit=""):
        cells = []
        for m in mats:
            try:
                cells.append(f"{conv(v(m['props'][key])):g}{unit}")
            except Exception:
                cells.append("—")
        rows.append(f"| {label} | " + " | ".join(cells) + " |")

    t_abs = float(params.get("t_abs_nm", 800))
    rows.append(f"| thickness [um] | {float(params.get('t_etl_nm', 20)) / 1000:g} | "
                f"{t_abs / 1000:g} | {float(params.get('t_htl_nm', 10)) / 1000:g} |")
    row("bandgap Eg [eV]", "Eg")
    row("electron affinity χ [eV]", "chi")
    row("dielectric permittivity (relative)", "epsr")
    row("CB effective DOS Nc [1/cm³]", "Nc")
    row("VB effective DOS Nv [1/cm³]", "Nv")
    row("electron mobility [cm²/Vs]", "mun")
    row("hole mobility [cm²/Vs]", "mup")
    rows.append("| shallow donor ND [1/cm³] | 1e19 | 0 | 0 |")
    rows.append("| shallow acceptor NA [1/cm³] | 0 | 0 | 1e18 |")
    taun = float(params.get("taun_ns", 38.7))
    s = float(params.get("s_ifc_cms", 1000))
    log(f"  레시피: 3층(n-i-p), τ={taun}ns → 흡수층 결함으로 환산 입력, 계면 S={s:g} cm/s")
    return "\n".join([
        "# SCAPS-1D 소자 레시피 (GUI 입력용)",
        "",
        "앱 materials.json(문헌 출처 있음)에서 자동 매핑. **숫자를 그대로 GUI에 입력**하고",
        "`.def`로 저장하면(예: `pin_mapi_app.def`) 이후 스크립트 배치 실행에 재사용됩니다.",
        "",
        "## 층 구조 (조명: ETL 쪽 = left contact 부터)",
        "front(=left) contact → SnO2 → MAPbI3 → NiOx → back contact",
        "",
        header, sep, *rows,
        "",
        "## 결함 (defects)",
        f"- MAPbI3 벌크: 중성 single level, midgap, τn=τp={taun}ns가 되도록",
        f"  Nt·σ·vth 설정 (예: vth=1e7cm/s, σ=1e-15cm² → Nt = 1/(τ·vth·σ) = "
        f"{1.0 / (taun * 1e-9 * 1e7 * 1e-15):.3g} cm⁻³)",
        f"- **계면 결함 2곳** (SnO2/MAPbI3, MAPbI3/NiOx): interface defect, neutral, midgap,",
        f"  S = {s:g} cm/s가 되도록 설정 — COMSOL IDL(τ=d/S) 케이스와 같은 정의",
        "",
        "## 접점·조명",
        "- 접점: 이상 옴익(플랫밴드 or 일함수를 각 층 다수캐리어 준위에 정렬) — COMSOL v0와 동일 조건",
        "- 조명: AM1.5G 1sun, ETL(front) 쪽 입사 / 반사 무시(COMSOL BL 모드와 비교할 것)",
        "",
        "## 실행·저장",
        f"- I-V: 0 → {float(params.get('v_max', 1.3)):g} V, 스텝 {float(params.get('v_step', 0.02)):g} V",
        "- 결과를 `File > Save results > I-V`로 .iv 저장 → 앱 ③ '결과 가져오기'에 업로드",
    ])


def _script(params):
    vmax = float(params.get("v_max", 1.3))
    step = float(params.get("v_step", 0.02))
    return f"""// SCAPS batch script draft (generated by app, 2026-07-08)
// NOTE: verify action/save syntax against the SCAPS manual 'script' chapter on first run.
// Precondition: build the device in the GUI per recipe.md and save as pin_mapi_app.def
load definitionfile "pin_mapi_app.def"
action iv startv 0.0000 stopv {vmax:.4f} increment {step:.4f}
calculate
save results iv "pin_mapi_app_out.iv"
quit
"""


def run(jid, params, log, case):
    jd = jobs.job_dir(jid)
    mode = str(params.get("mode", "export"))
    log(f"SCAPS-1D {mode}: n-i-p 레시피 + 스크립트 생성")
    (jd / "recipe.md").write_text(_recipe_md(params, log), encoding="utf-8")
    (jd / "batch.script").write_text(_script(params), encoding="ascii")
    common.write_readme(jid, "SCAPS-1D 사용 절차", [
        "1. (최초 1회) SCAPS GUI에서 recipe.md의 표대로 소자 생성 → `pin_mapi_app.def` 저장",
        "   (SCAPS의 def 폴더 또는 이 작업 폴더 — 스크립트와 같은 곳)",
        "2. 배치 실행: SCAPS의 script 기능으로 batch.script 실행 (⚠️ 문법 첫 실행 검증)",
        "   또는 GUI에서 직접 I-V 계산 후 .iv 저장",
        "3. .iv(및 .qe) 파일을 앱 ③ '결과 가져오기'에 업로드 → 지표·플롯 자동",
        "",
        "이 케이스의 목적: COMSOL IBC 케이스의 계면 재결합(IDL τ=d/S) 구현을",
        "SCAPS의 네이티브 계면 S와 **독립 대조**하는 것 (같은 물성·같은 S).",
    ])
    if mode == "local":
        exe = find_scaps()
        if not exe:
            raise RuntimeError("SCAPS 실행 파일이 설정되지 않았습니다 — ② 엔진 설정에 경로 입력 "
                               "(설치 전이면 export로 레시피만 생성하세요)")
        log(f"  scaps.exe 직접 구동 시도 (⚠️ CLI 인자 규약 미검증): {exe}")
        try:
            proc = subprocess.Popen([exe, str(jd / "batch.script")], cwd=str(jd))
            t0 = time.time()
            while proc.poll() is None:
                if time.time() - t0 > 600:
                    proc.kill()
                    raise RuntimeError("SCAPS 타임아웃(600s)")
                jobs.check_cancel(jid)
                time.sleep(2)
            log(f"  종료 코드 {proc.returncode}")
        except FileNotFoundError:
            raise RuntimeError("scaps.exe 실행 실패 — 경로 확인")
        ivs = sorted(jd.glob("*.iv"))
        if ivs:
            import_results(jid, params, log)
        else:
            log("  ⚠️ .iv 산출물이 없음 — CLI 구동 방식이 다를 수 있음. READ_ME_FIRST.md의 "
                "GUI 절차로 실행 후 '결과 가져오기'를 사용하세요")
    else:
        log("반출용 생성 완료 — recipe.md + batch.script + READ_ME_FIRST.md (④에서 다운로드)")


# ---------------- .iv/.qe 파서 (즉시 사용 가능 — 관용 텍스트 표 판독) ----------------

def _numeric_block(text, log, fname):
    """파일에서 숫자 표 블록(≥2열)을 추출. 헤더 줄(있으면)도 반환."""
    lines = text.splitlines()
    rows, header = [], ""
    for ln in lines:
        toks = re.split(r"[\s,;\t]+", ln.strip())
        vals = []
        ok = len(toks) >= 2
        for t in toks:
            if not t:
                continue
            try:
                vals.append(float(t.replace("E", "e")))
            except ValueError:
                ok = False
                break
        if ok and len(vals) >= 2:
            rows.append(vals)
        elif not rows and ln.strip():
            header = ln.strip()  # 숫자 블록 직전의 텍스트 줄을 헤더 후보로
    if not rows:
        raise RuntimeError(f"{fname}: 숫자 표를 찾지 못함")
    ncol = min(len(r) for r in rows)
    arr = np.array([r[:ncol] for r in rows], dtype=float)
    log(f"  [{fname}] {arr.shape[0]}행 × {ncol}열 (헤더 후보: {header[:80] or '없음'})")
    return arr, header


def _scaps_footer_metrics(text, log):
    """SCAPS가 파일에 적어주는 지표(Voc, Jsc, FF, eta)가 있으면 회수 (대조용)."""
    out = {}
    for key, pat in [("Voc_V", r"Voc\s*[=:]?\s*([\d.eE+-]+)\s*V"),
                     ("Jsc_mA_cm2", r"Jsc\s*[=:]?\s*([-\d.eE+]+)\s*mA/cm"),
                     ("FF_pct", r"FF\s*[=:]?\s*([\d.eE+-]+)\s*%"),
                     ("eta_pct", r"eta\s*[=:]?\s*([\d.eE+-]+)\s*%")]:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            out[key] = float(m.group(1))
    if out:
        log(f"  SCAPS 자체 지표(파일 기재): {out}")
    return out


def import_results(jid, params, log):
    jd = jobs.job_dir(jid)
    cand = [f for f in sorted(jd.iterdir())
            if f.suffix.lower() in (".iv", ".qe", ".txt", ".dat")
            and f.name not in ("log.txt",)]
    if not cand:
        raise RuntimeError("업로드된 .iv/.qe/.txt 파일이 없습니다")
    curves, qe_done = [], False
    for f in cand:
        text = f.read_text(encoding="utf-8", errors="replace")
        try:
            arr, header = _numeric_block(text, log, f.name)
        except RuntimeError as e:
            log(f"  {e} — 건너뜀")
            continue
        _scaps_footer_metrics(text, log)
        x = arr[:, 0]
        if f.suffix.lower() == ".qe" or (x.min() >= 250 and x.max() > 100):  # λ[nm]로 판단
            qe = arr[:, 1]
            qe = qe / 100.0 if qe.max() > 1.5 else qe  # % → fraction
            am = common.load_am15()
            H, C, Q = 6.62607015e-34, 299792458.0, 1.602176634e-19
            F = np.interp(x, am[:, 0], am[:, 1])
            phi = F * (x * 1e-9) / (H * C)
            jsc_qe = Q * np.trapezoid(qe * phi, x) * 0.1
            log(f"  [{f.name}] QE 스펙트럼: Jsc(QE적분) = {jsc_qe:.2f} mA/cm²")
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
            fig, ax = plt.subplots(figsize=(6, 4), dpi=110)
            ax.plot(x, qe * 100, lw=1.4)
            ax.set_xlabel("wavelength [nm]")
            ax.set_ylabel("QE [%]")
            ax.grid(alpha=0.3)
            fig.tight_layout()
            fig.savefig(jd / f"qe_{f.stem}.png")
            plt.close(fig)
            qe_done = True
        else:  # I-V: 1열 V, 2열 J[mA/cm²] (SCAPS 관용)
            curves.append((f.stem, x, arr[:, 1]))
    if curves:
        pin = 100.0
        plot = []
        for label, V, J in curves:
            o = np.argsort(V)
            m, Jgen = common.jv_metrics(V[o], J[o], pin, log)
            plot.append((label, V[o], Jgen))
            log(f"  [{label}] 앱 계산 지표: {m}")
            log("    (COMSOL 대조 시 주의: SCAPS 조명이 반사 무시 설정이면 COMSOL "
                "beer_lambert 모드와, 반사 포함이면 wave_optics 모드와 비교)")
        common.plot_jv(jid, plot, "jv_scaps.png", "SCAPS-1D J-V")
    if not curves and not qe_done:
        raise RuntimeError("판독된 곡선이 없습니다 — 파일이 SCAPS의 I-V/QE 저장본인지 확인")
    log("SCAPS 결과 판독 완료")
