"""SCAPS-1D 엔진 — 페로브스카이트 문헌 표준 1D 시뮬레이터 (겐트대, 연구용 무료).

강점: 계면 결함(재결합 속도 S)의 네이티브 지원 → 우리 COMSOL IDL(τ=d/S) 구현의
독립 대조군. 배포는 이메일 신청(비공개 아카이브)이라 설치는 사용자 몫.

.def(소자 정의) 파일 포맷은 버전 의존 바이너리성 텍스트라 **앱이 창작하지 않는다**
(임의 포맷 생성 금지 원칙). 대신:
  export : ① '레시피'(GUI에 입력할 물성 표 — materials.json 매핑, 출처 포함)
           ② SCAPS 스크립트 초안(.script — 액션 문법은 ⚠️ 첫 실행 검증)
           → 사용자가 GUI에서 소자를 한 번 만들어 .def로 저장하면, 이후 스크립트가
             그 .def를 불러 배치 실행 (SCAPS의 표준 사용 흐름)
  local  : scaps.exe에 스크립트 전달 시도 (⚠️ CLI 구동 방식 첫 실행 검증)
  import : SCAPS이 저장한 I-V(.iv)/QE(.qe) 파일 업로드 → 지표·플롯 (이건 즉시 사용 가능)
"""
import re
import subprocess
import time
from pathlib import Path

import numpy as np

from .. import jobs
from . import common, find_scaps


def _recipe_md(params, log):
    """GUI 입력용 물성 표 — materials.json에서 (SCAPS 입력 항목 명칭으로 변환)."""
    rows = []
    header = ("| 항목 (SCAPS 표기) | " + " | ".join(["SnO2 (ETL)", "MAPbI3 (흡수층)", "NiOx (HTL)"]) + " |")
    sep = "|---|---|---|---|"
    mats = [common.material("sno2"), common.material("mapbi3"), common.material("niox")]
    v = common.si_value

    def row(label, key, conv=lambda x: x, unit=""):
        cells = []
        for m in mats:
            try:
                cells.append(f"{conv(v(m['props'][key])):g}{unit}")
            except Exception:
                cells.append("—")
        rows.append(f"| {label} | " + " | ".join(cells) + " |")

    t_abs = float(params.get("t_abs_nm", 800))
    rows.append(f"| thickness [um] | {float(params.get('t_etl_nm', 20)) / 1000:g} | "
                f"{t_abs / 1000:g} | {float(params.get('t_htl_nm', 10)) / 1000:g} |")
    row("bandgap Eg [eV]", "Eg")
    row("electron affinity χ [eV]", "chi")
    row("dielectric permittivity (relative)", "epsr")
    row("CB effective DOS Nc [1/cm³]", "Nc")
    row("VB effective DOS Nv [1/cm³]", "Nv")
    row("electron mobility [cm²/Vs]", "mun")
    row("hole mobility [cm²/Vs]", "mup")
    rows.append("| shallow donor ND [1/cm³] | 1e19 | 0 | 0 |")
    rows.append("| shallow acceptor NA [1/cm³] | 0 | 0 | 1e18 |")
    taun = float(params.get("taun_ns", 38.7))
    s = float(params.get("s_ifc_cms", 1000))
    log(f"  레시피: 3층(n-i-p), τ={taun}ns → 흡수층 결함으로 환산 입력, 계면 S={s:g} cm/s")
    return "\n".join([
        "# SCAPS-1D 소자 레시피 (GUI 입력용)",
        "",
        "앱 materials.json(문헌 출처 있음)에서 자동 매핑. **숫자를 그대로 GUI에 입력**하고",
        "`.def`로 저장하면(예: `pin_mapi_app.def`) 이후 스크립트 배치 실행에 재사용됩니다.",
        "",
        "## 층 구조 (조명: ETL 쪽 = left contact 부터)",
        "front(=left) contact → SnO2 → MAPbI3 → NiOx → back contact",
        "",
        header, sep, *rows,
        "",
        "## 결함 (defects)",
        f"- MAPbI3 벌크: 중성 single level, midgap, τn=τp={taun}ns가 되도록",
        f"  Nt·σ·vth 설정 (예: vth=1e7cm/s, σ=1e-15cm² → Nt = 1/(τ·vth·σ) = "
        f"{1.0 / (taun * 1e-9 * 1e7 * 1e-15):.3g} cm⁻³)",
        f"- **계면 결함 2곳** (SnO2/MAPbI3, MAPbI3/NiOx): interface defect, neutral,",
        f"  **energetic distribution = uniform** (중심 midgap=0.775eV above highest EV,",
        f"  characteristic energy 0.1eV), σn=σp=1e-15cm², "
        f"Nt(total)={s / (1e-15 * 1e7):.3g} cm⁻²",
        f"  → S = σ·vth·Nt = {s:g} cm/s — COMSOL IDL(τ=d/S)과 같은 정의",
        "  ⚠️ single level 금지: 순방향 V≈Et(0.78V)에서 점유 스위칭으로 발산 (2026-07-13 실검증)",
        "",
        "## 수치 안정 필수 조정 (2026-07-13 GUI 실검증 — 없으면 1 sun V=0 발산)",
        "- NiOx: **χ=3.3, Eg=2.1** (문헌값 χ1.8/Eg3.6의 EV-고정 등가 — χ+Eg=5.4 유지,",
        "  ΔEc 2.1→0.6eV. 전자 차단은 여전히 완전 exp(-0.6/kT)≈4e-11, 정공 수송 불변)",
        "- SnO2: **χ=4.39 유지, Eg=1.66** (EV만 올려 ΔEv 2.38→0.6eV — 정공 차단 여전히 완전)",
        "- 근거: 문헌값 그대로면 소수캐리어 밀도가 1e-41까지 언더플로 → 뉴턴 발산 (원복 실험으로 확정)",
        "- **흡수 끄기 필수**: SnO2·NiOx 층의 Set absorption model에서 'sqrt() at Eg' 체크 해제(α=0)",
        "  — Eg 완화로 생기는 기생 흡수(20nm에 ~18%) 방지. MAPbI3 흡수는 그대로.",
        "- ⚠️ 대조 주의: 대리 (χ,Eg)는 CTL의 고유캐리어(ni)·소수캐리어 통계를 문헌값과",
        "  다르게 만듭니다 — COMSOL과의 비교는 '동일 물성' 정량 대조가 아니라 흡수층 τ·계면 S",
        "  중심의 준정량 대조로 취급하고, CTL 민감 지표는 참고용으로 보세요. (수치 대리모델임을",
        "  결과 보고에 명시)",
        "",
        "## 접점·조명",
        "- 접점: 이상 옴익(플랫밴드 or 일함수를 각 층 다수캐리어 준위에 정렬) — COMSOL v0와 동일 조건",
        "- 조명: AM1.5G 1sun, ETL(front) 쪽 입사 / 반사 무시(COMSOL BL 모드와 비교할 것)",
        "",
        "## 실행·저장",
        f"- I-V: 0 → {float(params.get('v_max', 1.3)):g} V, 스텝 {float(params.get('v_step', 0.02)):g} V",
        "- 결과를 `File > Save results > I-V`로 .iv 저장 → 앱 ③ '결과 가져오기'에 업로드",
    ])


def _script(params):
    vmax = float(params.get("v_max", 1.3))
    step = float(params.get("v_step", 0.02))
    npts = int(round(vmax / step)) + 1
    return f"""// SCAPS batch script (generated by app)
// Syntax verified 2026-07-13 against SCAPS 3.3.12 bundled example + GUI Execute script:
//  - filenames are NOT quoted (quotes -> 'definition file not found')
//  - action grammar: action <block>.<field> <value>   (example: action cv.startv -1)
//  - iv.doiv is inferred from the example's cv.docv -- if it errors, report the message
// Precondition: build the device once in the GUI per recipe.md, save as pin_mapi_app.def
// (in the SCAPS def folder). Illumination/light settings come from the def + GUI state.
clear all
load definitionfile pin_mapi_app.def
clear actions
action iv.doiv
action iv.startv 0.0000
action iv.stopv {vmax:.4f}
action iv.points {npts}
calculate singleshot
save results iv pin_mapi_app_out.iv
"""


def check(jid, params, log):
    """환경 점검: 실행 파일 탐지 + .iv 파서 자기검사 (동글 불필요)."""
    exe = find_scaps()
    if exe:
        log(f"SCAPS 실행 파일 OK: {exe} (⚠️ CLI 자동 구동은 첫 실행 때 함께 검증)")
    else:
        log("SCAPS 미탐지 — 겐트대(scaps@elis.ugent.be) 신청 후 설치, ② 엔진 설정에 경로 입력")
        log("  설치 전에도 가능: export(레시피·스크립트 생성) / GUI 계산 결과 .iv 업로드 판독")
    sample = "v(V)\t jtot(mA/cm2)\n 0.0\t-21.0\n 0.5\t-20.5\n 1.0\t-8.0\n 1.1\t 5.0\n"
    arr, _ = _numeric_block(sample, log, "selftest.iv")
    assert arr.shape == (4, 2), "파서 자기검사 실패"
    log(".iv 파서 자기검사 OK")
    log("SCAPS 점검 완료" + ("" if exe else " (실행 파일만 설치되면 끝)"))


def run(jid, params, log, case):
    jd = jobs.job_dir(jid)
    mode = str(params.get("mode", "export"))
    log(f"SCAPS-1D {mode}: n-i-p 레시피 + 스크립트 생성")
    (jd / "recipe.md").write_text(_recipe_md(params, log), encoding="utf-8")
    (jd / "batch.script").write_text(_script(params), encoding="ascii")
    common.write_readme(jid, "SCAPS-1D 사용 절차", [
        "1. (최초 1회) SCAPS GUI에서 recipe.md의 표대로 소자 생성 → `pin_mapi_app.def` 저장",
        "   (SCAPS의 def 폴더 또는 이 작업 폴더 — 스크립트와 같은 곳)",
        "2. 배치 실행: SCAPS의 script 기능으로 batch.script 실행 (⚠️ 문법 첫 실행 검증)",
        "   또는 GUI에서 직접 I-V 계산 후 .iv 저장",
        "3. .iv(및 .qe) 파일을 앱 ③ '결과 가져오기'에 업로드 → 지표·플롯 자동",
        "",
        "이 케이스의 목적: COMSOL IBC 케이스의 계면 재결합(IDL τ=d/S) 구현을",
        "SCAPS의 네이티브 계면 S와 **독립 대조**하는 것 (같은 물성·같은 S).",
    ])
    if mode == "local":
        exe = find_scaps()
        if not exe:
            raise RuntimeError("SCAPS 실행 파일이 설정되지 않았습니다 — ② 엔진 설정에 경로 입력 "
                               "(설치 전이면 export로 레시피만 생성하세요)")
        log(f"  scaps.exe 직접 구동 시도 (⚠️ CLI 인자 규약 미검증): {exe}")
        import shutil
        scaps_dir = Path(exe).parent
        try:  # GUI Execute script와 같은 조건이 되도록 script 폴더에도 복사
            shutil.copy2(jd / "batch.script", scaps_dir / "script" / "app_batch.script")
            log("  batch.script → SCAPS script 폴더 복사됨 (app_batch.script)")
        except Exception as e:
            log(f"  (script 폴더 복사 실패: {type(e).__name__} — 관리자 권한 필요할 수 있음)")
        t_start = time.time()
        try:
            proc = subprocess.Popen([exe, str(jd / "batch.script")], cwd=str(jd))
            while proc.poll() is None:
                if time.time() - t_start > 600:
                    proc.kill()
                    log("  SCAPS 600s 타임아웃 — 프로세스 종료 후 산출물 수집 시도")
                    break
                jobs.check_cancel(jid)
                time.sleep(2)
            if proc.returncode is not None:
                log(f"  종료 코드 {proc.returncode}")
        except FileNotFoundError:
            raise RuntimeError("scaps.exe 실행 실패 — 경로 확인")
        # 산출물 수집: SCAPS는 결과를 자기 results 폴더에 쓴다 (2026-07-13 확인)
        rdir = scaps_dir / "results"
        if rdir.exists():
            for f in rdir.glob("*.iv"):
                if f.stat().st_mtime >= t_start - 5:
                    shutil.copy2(f, jd / f.name)
                    log(f"  results 폴더에서 회수: {f.name}")
        ivs = sorted(jd.glob("*.iv"))
        if ivs:
            import_results(jid, params, log)
        else:
            log("  ⚠️ .iv 산출물이 없음 — CLI 구동 방식이 다를 수 있음. READ_ME_FIRST.md의 "
                "GUI 절차로 실행 후 '결과 가져오기'를 사용하세요")
    else:
        log("반출용 생성 완료 — recipe.md + batch.script + READ_ME_FIRST.md (④에서 다운로드)")


# ---------------- .iv/.qe 파서 (즉시 사용 가능 — 관용 텍스트 표 판독) ----------------

def _numeric_block(text, log, fname):
    """파일에서 숫자 표 블록(≥2열)을 추출. 헤더 줄(있으면)도 반환."""
    lines = text.splitlines()
    rows, header = [], ""
    for ln in lines:
        toks = re.split(r"[\s,;\t]+", ln.strip())
        vals = []
        ok = len(toks) >= 2
        for t in toks:
            if not t:
                continue
            try:
                vals.append(float(t.replace("E", "e")))
            except ValueError:
                ok = False
                break
        if ok and len(vals) >= 2:
            rows.append(vals)
        elif not rows and ln.strip():
            header = ln.strip()  # 숫자 블록 직전의 텍스트 줄을 헤더 후보로
    if not rows:
        raise RuntimeError(f"{fname}: 숫자 표를 찾지 못함")
    ncol = min(len(r) for r in rows)
    arr = np.array([r[:ncol] for r in rows], dtype=float)
    log(f"  [{fname}] {arr.shape[0]}행 × {ncol}열 (헤더 후보: {header[:80] or '없음'})")
    return arr, header


def _scaps_footer_metrics(text, log):
    """SCAPS가 파일에 적어주는 지표(Voc, Jsc, FF, eta)가 있으면 회수 (대조용)."""
    out = {}
    for key, pat in [("Voc_V", r"Voc\s*[=:]?\s*([\d.eE+-]+)\s*V"),
                     ("Jsc_mA_cm2", r"Jsc\s*[=:]?\s*([-\d.eE+]+)\s*mA/cm"),
                     ("FF_pct", r"FF\s*[=:]?\s*([\d.eE+-]+)\s*%"),
                     ("eta_pct", r"eta\s*[=:]?\s*([\d.eE+-]+)\s*%")]:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            out[key] = float(m.group(1))
    if out:
        log(f"  SCAPS 자체 지표(파일 기재): {out}")
    return out


def import_results(jid, params, log):
    jd = jobs.job_dir(jid)
    cand = [f for f in sorted(jd.iterdir())
            if f.suffix.lower() in (".iv", ".qe", ".txt", ".dat")
            and f.name not in ("log.txt",)]
    if not cand:
        raise RuntimeError("업로드된 .iv/.qe/.txt 파일이 없습니다")
    curves, qe_done = [], False
    for f in cand:
        text = f.read_text(encoding="utf-8", errors="replace")
        try:
            arr, header = _numeric_block(text, log, f.name)
        except RuntimeError as e:
            log(f"  {e} — 건너뜀")
            continue
        _scaps_footer_metrics(text, log)
        x = arr[:, 0]
        if f.suffix.lower() == ".qe" or (x.min() >= 250 and x.max() > 100):  # λ[nm]로 판단
            qe = arr[:, 1]
            qe = qe / 100.0 if qe.max() > 1.5 else qe  # % → fraction
            am = common.load_am15()
            H, C, Q = 6.62607015e-34, 299792458.0, 1.602176634e-19
            F = np.interp(x, am[:, 0], am[:, 1])
            phi = F * (x * 1e-9) / (H * C)
            jsc_qe = Q * np.trapezoid(qe * phi, x) * 0.1
            log(f"  [{f.name}] QE 스펙트럼: Jsc(QE적분) = {jsc_qe:.2f} mA/cm²")
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
            fig, ax = plt.subplots(figsize=(6, 4), dpi=110)
            ax.plot(x, qe * 100, lw=1.4)
            ax.set_xlabel("wavelength [nm]")
            ax.set_ylabel("QE [%]")
            ax.grid(alpha=0.3)
            fig.tight_layout()
            fig.savefig(jd / f"qe_{f.stem}.png")
            plt.close(fig)
            qe_done = True
        else:  # I-V: 1열 V, 2열 J[mA/cm²] (SCAPS 관용)
            # SCAPS I-V 패널 save는 쌓인 모든 시뮬레이션(dark 포함)을 한 파일에 이어
            # 저장할 수 있음 (2026-07-13 실검증: 513행 = 여러 스윕 연결) → V가 감소하는
            # 지점에서 스윕 분리, 곡선마다 dark/light 자동 라벨
            br = np.where(np.diff(x) < 0)[0] + 1
            segs = np.split(np.arange(x.size), br) if br.size else [np.arange(x.size)]
            for k, idx in enumerate(segs, 1):
                if idx.size < 3:
                    continue
                Vk, Jk = x[idx], arr[idx, 1]
                tag = "light" if abs(Jk[np.argmin(np.abs(Vk))]) > 0.5 else "dark"
                name = f.stem if len(segs) == 1 else f"{f.stem}#{k}({tag})"
                if len(segs) > 1:
                    log(f"  [{f.name}] 스윕 {k}/{len(segs)}: {idx.size}점 → {tag}")
                curves.append((name, Vk, Jk))
    if curves:
        pin = 100.0
        plot = []
        for label, V, J in curves:
            o = np.argsort(V)
            m, Jgen = common.jv_metrics(V[o], J[o], pin, log)
            plot.append((label, V[o], Jgen))
            log(f"  [{label}] 앱 계산 지표: {m}")
            log("    (COMSOL 대조 시 주의: SCAPS 조명이 반사 무시 설정이면 COMSOL "
                "beer_lambert 모드와, 반사 포함이면 wave_optics 모드와 비교)")
        common.plot_jv(jid, plot, "jv_scaps.png", "SCAPS-1D J-V")
    if not curves and not qe_done:
        raise RuntimeError("판독된 곡선이 없습니다 — 파일이 SCAPS의 I-V/QE 저장본인지 확인")
    log("SCAPS 결과 판독 완료")
